name = "portfolio-victer"
main = "workers/site.ts"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "portfolio-assets"

[env.staging]
name = "portfolio-victer-staging"

[env.production]
name = "portfolio-victer-production"
